apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-srv
  namespace: bookshop-prod
spec:
  replicas: 8
  template:
    spec:
      containers:
        - name: bookshop-srv
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"